export const CREATE_CARD = 'CREATE_CARD'
export const REMOVE_CARDS = 'REMOVE_CARDS'
export const UPDATE_CARD = 'UPDATE_CARD'
export const SELECT_CARD = 'SELECT_CARD'
export const FETCH_CARDS = 'FETCH_CARDS'
